newspaper/newsapp/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import NewsList, NewsDetail, NewsSearch, NewsCreate, ArticleList, ArticleCreate, NewsEdit, ArticleEdit, \
   NewsDelete, ArticleDelete, subscriptions

urlpatterns = [
    path('news/', NewsList.as_view(), name='news_list'),
    path('articles/', ArticleList.as_view(), name='article_list'),
    path('<int:pk>', NewsDetail.as_view(), name='news_detail'),
    path('news/search/', NewsSearch.as_view(), name='news_search'),
    path('news/create/', NewsCreate.as_view(), name='news_create'),
    path('articles/create', ArticleCreate.as_view(), name='article_create'),
    path('news/<int:pk>/edit', NewsEdit.as_view(), name='news_edit'),
    path('articles/<int:pk>/edit', ArticleEdit.as_view(), name='articles_edit'),
    path('news/<int:pk>/delete', NewsDelete.as_view(), name='news_delete'),
    path('articles/<int:pk>/delete', ArticleDelete.as_view(), name='article_delete'),
    # path('subscriptions/', subscriptions, name='subscriptions'),
]

newspaper/newspaper/urls.py
from django.contrib import admin
from django.urls import path, include

from newsapp.views import subscriptions

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('newspaper/', include('newsapp.urls')),
    path('subscriptions/', subscriptions, name='subscriptions'),
]

newspaper/newsapp/models.py
from django.contrib.auth.models import User
from datetime import datetime, timezone

from django.db import models
from django.db.models import Sum
from django.urls import reverse
from django.template.defaultfilters import truncatewords




class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_rate = models.IntegerField(default=0)

    def update_rating(self):

        sum_rating = self.post_set.aggregate(post_rating=Sum('post_rate'))
        result_sum_rating = 0

        try:
            result_sum_rating += sum_rating.get('post_rating')
        except TypeError:
            result_sum_rating = 0

        sum_comment_rating = self.author.comment_set.aggregate(comment_rating=Sum('comment_rate'))
        result_sum_comment_rating = 0
        result_sum_comment_rating += sum_comment_rating.get('comment_rating')
        self.user_rate = result_sum_rating * 3 + result_sum_comment_rating
        self.save()


class Category(models.Model):
    category_name = models.CharField(max_length=255, unique=True)
    subscribers = models.ManyToManyField(User, through='Subscriber', related_name='categories')

    def __str__(self):
        return self.category_name


class Post(models.Model):
    Article_or_News = [
        ('A', 'Статья'),
        ('N', 'Новость')
    ]
    heading = models.CharField(max_length=50)
    text = models.TextField()
    post_rate = models.IntegerField(default=0)
    date_time = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    choice = models.CharField(max_length=1, choices=Article_or_News, default='N')
    categories = models.ManyToManyField(Category, through='PostCategory')

    def __str__(self):
        return f'{self.heading.title()}: {self.text[:20]}'

    def like(self):
        self.post_rate += 1
        self.save()

    def dislike(self):
        self.post_rate -= 1
        self.save()

    def preview(self):
        return self.text[:125] + "..."

    def get_absolute_url(self):
        return reverse('news_detail', args=[str(self.id)])




class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.TextField(blank=True)
    date_time = models.DateTimeField(auto_now_add=True)
    comment_rate = models.IntegerField(default=0)

    def like(self):
        self.comment_rate += 1
        self.save()

    def dislike(self):
        self.comment_rate -= 1
        self.save()

class Subscriber(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

newspaper/templates/all_articles.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
    {% if posts %}
   <h1>Количество статей:</h1>

 <h3>{{ page_obj.paginator.count }}</h3>
   <hr>
{% if perms.newsapp.add_post %}
<a href="../articles/create">Создать статью</a>
{% endif %}

       <table>
           <tr>
               <td> Заголовок</td>
               <td>Дата публикации</td>
               <td>Текст</td>
               {% if perms.newsapp.change_post %}
               <td>Действие</td>
               {% endif %}

           </tr>

           {% for post in posts %}
           {% if post.choice == 'A' %}
           <tr>
               <td> {{post.heading|censor}} </td>
               <td> {{post.date_time|date:'d.m.Y'}} </td>
               <td> {{post.text|truncatewords:20|censor}} </td>
               {% if perms.newsapp.change_post %}
               <td><a href="../articles/{{post.id}}/edit">Изменить</a></td>
               {% endif %}
           </tr>
           {% endif %}
           {% endfor %}
       </table>
   {% else %}
       <h2>Статей нет!</h2>
   {% endif %}


    {% if page_obj.previous_page_number != 1 %}
        <a href="?page=1"><<</a>
        ...
        <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% if page_obj.previous_page_number == 1 %}
<a href = "?page=1">1</a>
{% endif %}

{{ page_obj.number }}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
{% if paginator.num_pages != page_obj.next_page_number %}
...
<a href="?page={{ page_obj.paginator.num_pages }}"> >> </a>
{% endif %}
{% endif %}

{% endblock content %}

newspaper/templates/all_news.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
    {% if posts %}
   <h1>Количество новостей:</h1>
 <h3>{{ page_obj.paginator.count}}</h3>
   <hr>
{% if perms.newsapp.add_post %}
<a href="../news/create/">Создать новость</a>
{% endif %}
       <table>
           <tr>
               <td> Заголовок</td>
               <td>Дата публикации</td>
               <td>Текст</td>
               {% if perms.newsapp.change_post %}
               <td>Действие</td>
               {% endif %}

           </tr>

           {% for post in posts %}
           {% if post.choice == 'N' %}
           <tr>
               <td> {{post.heading|censor}} </td>
               <td> {{post.date_time|date:'d.m.Y'}} </td>
               <td> {{post.text|truncatewords:20|censor}} </td>
               {% if perms.newsapp.change_post %}
               <td><a href="../news/{{post.id}}/edit">Изменить</a></td>
               {% endif %}

           </tr>
           {% endif %}
           {% endfor %}
       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}


    {% if page_obj.previous_page_number != 1 %}
        <a href="?page=1"><<</a>
        ...
        <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% if page_obj.previous_page_number == 1 %}
<a href = "?page=1">1</a>
{% endif %}

{{ page_obj.number }}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
{% if paginator.num_pages != page_obj.next_page_number %}
...
<a href="?page={{ page_obj.paginator.num_pages }}"> >> </a>
{% endif %}
{% endif %}

{% endblock content %}

newspaper/templates/article_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Статья</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

newspaper/templates/articles_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление Статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.heading }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

newspaper/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Новые статьи за послежнюю неделю:</h2>
<ul>
    {% for post in posts %}
    <li><a href = "{{ link }}{{ post.get_absolute_url }}">{{ post.heading }}</a></li>
    {% endfor %}
</ul>
</body>
</html>

newspaper/templates/news.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}
{% load custom_filters %}


{% block title %}
Post
{% endblock title %}

{% block content %}
<h1>{{ posts.heading.capitalize|censor }}</h1>
<h2>Дата публикации:
    {{ posts.date_time|date:'d.m.Y' }}</h2>
<h3> {{ posts.text.capitalize|censor }} </h3>

{% endblock content %}

newspaper/templates/news_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

newspaper/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление Новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.heading }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

newspaper/templates/news_search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Post
{% endblock title %}

{% block content %}
<h1>Поиск новостей</h1>
<form action="" method="get">
    {{ filterset.form.as_p }}
    <input type="submit" value="Найти" />
</form>

   <hr>
   {% if posts %}
       <table>
           <tr>
               <td> Заголовок</td>
               <td>Дата публикации</td>
               <td>Текст</td>
           </tr>
           {% for post in posts %}
           {% if post.choice == 'N' %}
           <tr>
               <td> {{post.heading|censor}} </td>
               <td> {{post.date_time|date:'d.m.Y'}} </td>
               <td> {{post.text|truncatewords:20|censor}} </td>
           </tr>
           {% endif %}
           {% endfor %}
       </table>
   {% else %}
       <h2>Постов нет!</h2>
   {% endif %}


    {% if page_obj.previous_page_number != 1 %}
        <a href="?{% url_replace page=1 %}"><<</a>
        ...
        <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% if page_obj.previous_page_number == 1 %}
<a href = "?{% url_replace page=1 %}">1</a>
{% endif %}

{{ page_obj.number }}

{% if page_obj.has_next %}
<a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
{% if paginator.num_pages != page_obj.next_page_number %}
...
<a href="?{% url_replace page=page_obj.paginator.num_pages %}"> >> </a>
{% endif %}
{% endif %}
{% endblock content %}

newspaper/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Новая <a href="{{ link }}">статья</a> в категории, на которую ты подписан</h2>
<p>{{ text }}</p>
</body>
</html>

newspaper/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.category_name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}